-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity group3_mergeSort is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    arr_read : IN STD_LOGIC_VECTOR (31 downto 0);
    n : IN STD_LOGIC_VECTOR (31 downto 0);
    ap_return : OUT STD_LOGIC_VECTOR (31 downto 0) );
end;


architecture behav of group3_mergeSort is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (13 downto 0) := "00000000000100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (13 downto 0) := "00000000001000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (13 downto 0) := "00000000010000";
    constant ap_ST_fsm_state6 : STD_LOGIC_VECTOR (13 downto 0) := "00000000100000";
    constant ap_ST_fsm_state7 : STD_LOGIC_VECTOR (13 downto 0) := "00000001000000";
    constant ap_ST_fsm_state8 : STD_LOGIC_VECTOR (13 downto 0) := "00000010000000";
    constant ap_ST_fsm_state9 : STD_LOGIC_VECTOR (13 downto 0) := "00000100000000";
    constant ap_ST_fsm_state10 : STD_LOGIC_VECTOR (13 downto 0) := "00001000000000";
    constant ap_ST_fsm_state11 : STD_LOGIC_VECTOR (13 downto 0) := "00010000000000";
    constant ap_ST_fsm_state12 : STD_LOGIC_VECTOR (13 downto 0) := "00100000000000";
    constant ap_ST_fsm_state13 : STD_LOGIC_VECTOR (13 downto 0) := "01000000000000";
    constant ap_ST_fsm_state14 : STD_LOGIC_VECTOR (13 downto 0) := "10000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_6 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000110";
    constant ap_const_lv32_7 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000111";
    constant ap_const_lv32_8 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001000";
    constant ap_const_lv32_9 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001001";
    constant ap_const_lv32_A : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001010";
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv32_B : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001011";
    constant ap_const_lv32_5 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000101";
    constant ap_const_lv32_C : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001100";
    constant ap_const_lv32_D : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001101";
    constant ap_const_lv32_FFFFFFFF : STD_LOGIC_VECTOR (31 downto 0) := "11111111111111111111111111111111";
    constant ap_const_lv33_1 : STD_LOGIC_VECTOR (32 downto 0) := "000000000000000000000000000000001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (13 downto 0) := "00000000000001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal reg_192 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal icmp_ln10_fu_234_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal sub7_fu_199_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub7_reg_445 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln13_fu_223_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln13_reg_456 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal icmp_ln7_fu_218_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal l2_fu_229_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal l2_reg_462 : STD_LOGIC_VECTOR (31 downto 0);
    signal h2_1_fu_264_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal h2_1_reg_476 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal h1_fu_271_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal h1_reg_485 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln22_fu_281_p2 : STD_LOGIC_VECTOR (32 downto 0);
    signal sub_ln22_reg_491 : STD_LOGIC_VECTOR (32 downto 0);
    signal icmp_ln22_fu_288_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln22_reg_496 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln22_fu_292_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln22_reg_500 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln22_fu_338_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln22_reg_520 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state7 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state7 : signal is "none";
    signal icmp_ln22_1_loc_load_load_fu_316_p1 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln31_fu_350_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state8 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state8 : signal is "none";
    signal empty_fu_355_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal empty_reg_530 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_CS_fsm_state9 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state9 : signal is "none";
    signal arr_0_load11_reg_535 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state10 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state10 : signal is "none";
    signal add_ln35_1_fu_375_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln35_1_reg_540 : STD_LOGIC_VECTOR (31 downto 0);
    signal l1_fu_381_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_CS_fsm_state11 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state11 : signal is "none";
    signal temp_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal temp_ce0 : STD_LOGIC;
    signal temp_we0 : STD_LOGIC;
    signal temp_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal temp_q0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_done : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_idle : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_ready : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_ce0 : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_we0 : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_done : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_idle : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_ready : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_ce0 : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_we0 : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_out_ap_vld : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out_ap_vld : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out : STD_LOGIC_VECTOR (63 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out_ap_vld : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out_ap_vld : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_i_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_i_1_out_ap_vld : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out_ap_vld : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_idle : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_ready : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_ce0 : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_we0 : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_done : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_idle : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_ready : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_ce0 : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_we0 : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_d0 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_done : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_idle : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_ready : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_address0 : STD_LOGIC_VECTOR (4 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_ce0 : STD_LOGIC;
    signal grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out_ap_vld : STD_LOGIC;
    signal k_reg_82 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_phi_mux_k_4_lcssa_phi_fu_120_p4 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_block_state11_on_subcall_done : BOOLEAN;
    signal l1_2_reg_94 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_4_reg_106 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_4_lcssa_reg_116 : STD_LOGIC_VECTOR (31 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state12 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state12 : signal is "none";
    signal grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state6 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state6 : signal is "none";
    signal phi_ln22_1_loc_fu_58 : STD_LOGIC_VECTOR (31 downto 0);
    signal k_1_loc_fu_50 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln22_1_loc_fu_42 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg : STD_LOGIC := '0';
    signal grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg : STD_LOGIC := '0';
    signal grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state13 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state13 : signal is "none";
    signal ap_CS_fsm_state14 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state14 : signal is "none";
    signal arr_0_fu_38 : STD_LOGIC_VECTOR (31 downto 0);
    signal size_fu_34 : STD_LOGIC_VECTOR (31 downto 0);
    signal size_2_fu_239_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal h2_fu_249_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal icmp_ln15_fu_253_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln15_fu_258_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln22_fu_277_p1 : STD_LOGIC_VECTOR (32 downto 0);
    signal add_ln29_fu_319_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sext_ln22_1_fu_324_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln22_2_fu_328_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln22_fu_334_p1 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln31_1_fu_346_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal select_ln35_fu_359_p3 : STD_LOGIC_VECTOR (31 downto 0);
    signal add_ln35_fu_369_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal sub_ln35_fu_364_p2 : STD_LOGIC_VECTOR (31 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (13 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ST_fsm_state6_blk : STD_LOGIC;
    signal ap_ST_fsm_state7_blk : STD_LOGIC;
    signal ap_ST_fsm_state8_blk : STD_LOGIC;
    signal ap_ST_fsm_state9_blk : STD_LOGIC;
    signal ap_ST_fsm_state10_blk : STD_LOGIC;
    signal ap_ST_fsm_state11_blk : STD_LOGIC;
    signal ap_ST_fsm_state12_blk : STD_LOGIC;
    signal ap_ST_fsm_state13_blk : STD_LOGIC;
    signal ap_ST_fsm_state14_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component group3_mergeSort_Pipeline_VITIS_LOOP_39_6 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln39 : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln7 : IN STD_LOGIC_VECTOR (31 downto 0);
        temp_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        temp_ce0 : OUT STD_LOGIC;
        temp_we0 : OUT STD_LOGIC;
        temp_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_0 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component group3_mergeSort_Pipeline_VITIS_LOOP_22_3 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        k : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln22_3 : IN STD_LOGIC_VECTOR (32 downto 0);
        l1_2_cast2 : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln22 : IN STD_LOGIC_VECTOR (31 downto 0);
        l1_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        h1 : IN STD_LOGIC_VECTOR (31 downto 0);
        icmp_ln22 : IN STD_LOGIC_VECTOR (0 downto 0);
        temp_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        temp_ce0 : OUT STD_LOGIC;
        temp_we0 : OUT STD_LOGIC;
        temp_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        phi_ln22_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        phi_ln22_out_ap_vld : OUT STD_LOGIC;
        phi_ln22_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        phi_ln22_1_out_ap_vld : OUT STD_LOGIC;
        indvars_iv1_out : OUT STD_LOGIC_VECTOR (63 downto 0);
        indvars_iv1_out_ap_vld : OUT STD_LOGIC;
        k_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        k_1_out_ap_vld : OUT STD_LOGIC;
        i_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        i_1_out_ap_vld : OUT STD_LOGIC;
        icmp_ln22_1_out : OUT STD_LOGIC_VECTOR (0 downto 0);
        icmp_ln22_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component group3_mergeSort_Pipeline_VITIS_LOOP_29_4 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln29_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln29 : IN STD_LOGIC_VECTOR (31 downto 0);
        temp_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        temp_ce0 : OUT STD_LOGIC;
        temp_we0 : OUT STD_LOGIC;
        temp_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln29_1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component group3_mergeSort_Pipeline_VITIS_LOOP_31_5 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        sext_ln31_2 : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln31 : IN STD_LOGIC_VECTOR (31 downto 0);
        temp_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        temp_ce0 : OUT STD_LOGIC;
        temp_we0 : OUT STD_LOGIC;
        temp_d0 : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_0 : IN STD_LOGIC_VECTOR (31 downto 0);
        sext_ln31_1 : IN STD_LOGIC_VECTOR (31 downto 0) );
    end component;


    component group3_mergeSort_Pipeline_VITIS_LOOP_42_7 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        n : IN STD_LOGIC_VECTOR (31 downto 0);
        temp_address0 : OUT STD_LOGIC_VECTOR (4 downto 0);
        temp_ce0 : OUT STD_LOGIC;
        temp_q0 : IN STD_LOGIC_VECTOR (31 downto 0);
        arr_1_out : OUT STD_LOGIC_VECTOR (31 downto 0);
        arr_1_out_ap_vld : OUT STD_LOGIC );
    end component;


    component group3_mergeSort_temp_RAM_AUTO_1R1W IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce0 : IN STD_LOGIC;
        we0 : IN STD_LOGIC;
        d0 : IN STD_LOGIC_VECTOR (31 downto 0);
        q0 : OUT STD_LOGIC_VECTOR (31 downto 0) );
    end component;



begin
    temp_U : component group3_mergeSort_temp_RAM_AUTO_1R1W
    generic map (
        DataWidth => 32,
        AddressRange => 30,
        AddressWidth => 5)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => temp_address0,
        ce0 => temp_ce0,
        we0 => temp_we0,
        d0 => temp_d0,
        q0 => temp_q0);

    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128 : component group3_mergeSort_Pipeline_VITIS_LOOP_39_6
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start,
        ap_done => grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_done,
        ap_idle => grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_idle,
        ap_ready => grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_ready,
        sext_ln39 => k_reg_82,
        sext_ln7 => n,
        temp_address0 => grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_address0,
        temp_ce0 => grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_ce0,
        temp_we0 => grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_we0,
        temp_d0 => grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_d0,
        arr_0 => reg_192);

    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137 : component group3_mergeSort_Pipeline_VITIS_LOOP_22_3
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start,
        ap_done => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_done,
        ap_idle => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_idle,
        ap_ready => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_ready,
        k => k_reg_82,
        sext_ln22_3 => sub_ln22_reg_491,
        l1_2_cast2 => l1_2_reg_94,
        sext_ln22 => k_reg_82,
        l1_2 => l1_2_reg_94,
        h1 => h1_reg_485,
        icmp_ln22 => xor_ln22_reg_500,
        temp_address0 => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_address0,
        temp_ce0 => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_ce0,
        temp_we0 => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_we0,
        temp_d0 => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_d0,
        arr_0 => reg_192,
        phi_ln22_out => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_out,
        phi_ln22_out_ap_vld => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_out_ap_vld,
        phi_ln22_1_out => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out,
        phi_ln22_1_out_ap_vld => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out_ap_vld,
        indvars_iv1_out => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out,
        indvars_iv1_out_ap_vld => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out_ap_vld,
        k_1_out => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out,
        k_1_out_ap_vld => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out_ap_vld,
        i_1_out => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_i_1_out,
        i_1_out_ap_vld => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_i_1_out_ap_vld,
        icmp_ln22_1_out => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out,
        icmp_ln22_1_out_ap_vld => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out_ap_vld);

    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160 : component group3_mergeSort_Pipeline_VITIS_LOOP_29_4
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start,
        ap_done => grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done,
        ap_idle => grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_idle,
        ap_ready => grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_ready,
        sext_ln29_2 => k_1_loc_fu_50,
        sext_ln29 => grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_i_1_out,
        temp_address0 => grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_address0,
        temp_ce0 => grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_ce0,
        temp_we0 => grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_we0,
        temp_d0 => grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_d0,
        arr_0 => reg_192,
        sext_ln29_1 => h1_reg_485);

    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169 : component group3_mergeSort_Pipeline_VITIS_LOOP_31_5
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start,
        ap_done => grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_done,
        ap_idle => grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_idle,
        ap_ready => grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_ready,
        sext_ln31_2 => k_4_reg_106,
        sext_ln31 => l2_reg_462,
        temp_address0 => grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_address0,
        temp_ce0 => grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_ce0,
        temp_we0 => grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_we0,
        temp_d0 => grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_d0,
        arr_0 => arr_0_load11_reg_535,
        sext_ln31_1 => h2_1_reg_476);

    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179 : component group3_mergeSort_Pipeline_VITIS_LOOP_42_7
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start,
        ap_done => grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_done,
        ap_idle => grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_idle,
        ap_ready => grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_ready,
        n => n,
        temp_address0 => grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_address0,
        temp_ce0 => grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_ce0,
        temp_q0 => temp_q0,
        arr_1_out => grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out,
        arr_1_out_ap_vld => grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_ready = ap_const_logic_1)) then 
                    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln22_1_loc_load_load_fu_316_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_ready = ap_const_logic_1)) then 
                    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state10)) then 
                    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_ready = ap_const_logic_1)) then 
                    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg <= ap_const_logic_0;
            else
                if (((icmp_ln10_fu_234_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_ready = ap_const_logic_1)) then 
                    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_CS_fsm_state13)) then 
                    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_ready = ap_const_logic_1)) then 
                    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;


    arr_0_fu_38_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                arr_0_fu_38 <= arr_read;
            elsif (((grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out_ap_vld = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then 
                arr_0_fu_38 <= grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out;
            end if; 
        end if;
    end process;

    k_4_lcssa_reg_116_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln22_reg_496 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then 
                k_4_lcssa_reg_116 <= k_4_reg_106;
            elsif (((icmp_ln22_reg_496 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                k_4_lcssa_reg_116 <= add_ln35_1_reg_540;
            end if; 
        end if;
    end process;

    k_4_reg_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln22_1_loc_load_load_fu_316_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then 
                k_4_reg_106 <= k_1_loc_fu_50;
            elsif (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done = ap_const_logic_1))) then 
                k_4_reg_106 <= add_ln31_fu_350_p2;
            end if; 
        end if;
    end process;

    k_reg_82_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                k_reg_82 <= ap_phi_mux_k_4_lcssa_phi_fu_120_p4;
            elsif (((icmp_ln7_fu_218_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                k_reg_82 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    l1_2_reg_94_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
                l1_2_reg_94 <= l1_fu_381_p2;
            elsif (((icmp_ln7_fu_218_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
                l1_2_reg_94 <= ap_const_lv32_0;
            end if; 
        end if;
    end process;

    size_fu_34_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                size_fu_34 <= ap_const_lv32_1;
            elsif (((icmp_ln10_fu_234_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then 
                size_fu_34 <= size_2_fu_239_p2;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln7_fu_218_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                add_ln13_reg_456 <= add_ln13_fu_223_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state10)) then
                add_ln35_1_reg_540 <= add_ln35_1_fu_375_p2;
                arr_0_load11_reg_535 <= arr_0_fu_38;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln22_reg_496 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                empty_reg_530 <= empty_fu_355_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state5)) then
                h1_reg_485 <= h1_fu_271_p2;
                icmp_ln22_reg_496 <= icmp_ln22_fu_288_p2;
                sub_ln22_reg_491 <= sub_ln22_fu_281_p2;
                xor_ln22_reg_500 <= xor_ln22_fu_292_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                h2_1_reg_476 <= h2_1_fu_264_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out_ap_vld = ap_const_logic_1))) then
                icmp_ln22_1_loc_fu_42 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out_ap_vld = ap_const_logic_1))) then
                k_1_loc_fu_50 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                l2_reg_462 <= l2_fu_229_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out_ap_vld = ap_const_logic_1))) then
                phi_ln22_1_loc_fu_58 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((icmp_ln10_fu_234_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3)))) then
                reg_192 <= arr_0_fu_38;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln22_1_loc_load_load_fu_316_p1 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                select_ln22_reg_520 <= select_ln22_fu_338_p3;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state1)) then
                sub7_reg_445 <= sub7_fu_199_p2;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, ap_CS_fsm_state3, icmp_ln10_fu_234_p2, ap_CS_fsm_state2, icmp_ln7_fu_218_p2, icmp_ln22_reg_496, ap_CS_fsm_state7, icmp_ln22_1_loc_load_load_fu_316_p1, ap_CS_fsm_state8, ap_CS_fsm_state9, ap_CS_fsm_state11, grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_done, grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_done, grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done, grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_done, ap_block_state11_on_subcall_done, ap_CS_fsm_state12, ap_CS_fsm_state6, ap_CS_fsm_state14)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((icmp_ln7_fu_218_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                else
                    ap_NS_fsm <= ap_ST_fsm_state3;
                end if;
            when ap_ST_fsm_state3 => 
                if (((icmp_ln10_fu_234_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state3))) then
                    ap_NS_fsm <= ap_ST_fsm_state12;
                else
                    ap_NS_fsm <= ap_ST_fsm_state4;
                end if;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state6;
            when ap_ST_fsm_state6 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state6) and (grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state7;
                else
                    ap_NS_fsm <= ap_ST_fsm_state6;
                end if;
            when ap_ST_fsm_state7 => 
                if (((icmp_ln22_1_loc_load_load_fu_316_p1 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state7))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state8 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state8) and (grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state9;
                else
                    ap_NS_fsm <= ap_ST_fsm_state8;
                end if;
            when ap_ST_fsm_state9 => 
                if (((icmp_ln22_reg_496 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state9))) then
                    ap_NS_fsm <= ap_ST_fsm_state11;
                else
                    ap_NS_fsm <= ap_ST_fsm_state10;
                end if;
            when ap_ST_fsm_state10 => 
                ap_NS_fsm <= ap_ST_fsm_state11;
            when ap_ST_fsm_state11 => 
                if (((ap_const_boolean_0 = ap_block_state11_on_subcall_done) and (ap_const_logic_1 = ap_CS_fsm_state11))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state11;
                end if;
            when ap_ST_fsm_state12 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state12) and (grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state13;
                else
                    ap_NS_fsm <= ap_ST_fsm_state12;
                end if;
            when ap_ST_fsm_state13 => 
                ap_NS_fsm <= ap_ST_fsm_state14;
            when ap_ST_fsm_state14 => 
                if (((grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_done = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state14))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state14;
                end if;
            when others =>  
                ap_NS_fsm <= "XXXXXXXXXXXXXX";
        end case;
    end process;
    add_ln13_fu_223_p2 <= std_logic_vector(unsigned(size_fu_34) + unsigned(ap_const_lv32_FFFFFFFF));
    add_ln29_fu_319_p2 <= std_logic_vector(unsigned(l1_2_reg_94) + unsigned(add_ln13_reg_456));
    add_ln31_1_fu_346_p2 <= std_logic_vector(unsigned(phi_ln22_1_loc_fu_58) + unsigned(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_out));
    add_ln31_fu_350_p2 <= std_logic_vector(unsigned(add_ln31_1_fu_346_p2) + unsigned(select_ln22_reg_520));
    add_ln35_1_fu_375_p2 <= std_logic_vector(unsigned(add_ln35_fu_369_p2) + unsigned(sub_ln35_fu_364_p2));
    add_ln35_fu_369_p2 <= std_logic_vector(unsigned(select_ln35_fu_359_p3) + unsigned(k_4_reg_106));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state10 <= ap_CS_fsm(9);
    ap_CS_fsm_state11 <= ap_CS_fsm(10);
    ap_CS_fsm_state12 <= ap_CS_fsm(11);
    ap_CS_fsm_state13 <= ap_CS_fsm(12);
    ap_CS_fsm_state14 <= ap_CS_fsm(13);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);
    ap_CS_fsm_state6 <= ap_CS_fsm(5);
    ap_CS_fsm_state7 <= ap_CS_fsm(6);
    ap_CS_fsm_state8 <= ap_CS_fsm(7);
    ap_CS_fsm_state9 <= ap_CS_fsm(8);
    ap_ST_fsm_state10_blk <= ap_const_logic_0;

    ap_ST_fsm_state11_blk_assign_proc : process(ap_block_state11_on_subcall_done)
    begin
        if ((ap_const_boolean_1 = ap_block_state11_on_subcall_done)) then 
            ap_ST_fsm_state11_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state11_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state12_blk_assign_proc : process(grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_done)
    begin
        if ((grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state12_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state12_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state13_blk <= ap_const_logic_0;

    ap_ST_fsm_state14_blk_assign_proc : process(grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_done)
    begin
        if ((grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state14_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state14_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_ST_fsm_state6_blk_assign_proc : process(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_done)
    begin
        if ((grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state6_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state6_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state7_blk <= ap_const_logic_0;

    ap_ST_fsm_state8_blk_assign_proc : process(grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done)
    begin
        if ((grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state8_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state8_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state9_blk <= ap_const_logic_0;

    ap_block_state11_on_subcall_done_assign_proc : process(icmp_ln22_reg_496, grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_done)
    begin
                ap_block_state11_on_subcall_done <= ((icmp_ln22_reg_496 = ap_const_lv1_0) and (grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_done = ap_const_logic_0));
    end process;


    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state2, icmp_ln7_fu_218_p2)
    begin
        if ((((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)) or ((icmp_ln7_fu_218_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_phi_mux_k_4_lcssa_phi_fu_120_p4_assign_proc : process(icmp_ln22_reg_496, add_ln35_1_reg_540, ap_CS_fsm_state11, k_4_lcssa_reg_116)
    begin
        if (((icmp_ln22_reg_496 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            ap_phi_mux_k_4_lcssa_phi_fu_120_p4 <= add_ln35_1_reg_540;
        else 
            ap_phi_mux_k_4_lcssa_phi_fu_120_p4 <= k_4_lcssa_reg_116;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state2, icmp_ln7_fu_218_p2)
    begin
        if (((icmp_ln7_fu_218_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state2))) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    ap_return <= arr_0_fu_38;
    empty_fu_355_p2 <= "1" when (signed(h2_1_reg_476) > signed(l2_reg_462)) else "0";
    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg;
    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start <= grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg;
    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start <= grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg;
    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start <= grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg;
    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start <= grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg;
    h1_fu_271_p2 <= std_logic_vector(unsigned(l2_reg_462) + unsigned(ap_const_lv32_FFFFFFFF));
    h2_1_fu_264_p3 <= 
        sub7_reg_445 when (xor_ln15_fu_258_p2(0) = '1') else 
        h2_fu_249_p2;
    h2_fu_249_p2 <= std_logic_vector(unsigned(l2_reg_462) + unsigned(add_ln13_reg_456));
    icmp_ln10_fu_234_p2 <= "1" when (signed(l2_fu_229_p2) < signed(n)) else "0";
    icmp_ln15_fu_253_p2 <= "1" when (signed(h2_fu_249_p2) < signed(n)) else "0";
    icmp_ln22_1_loc_load_load_fu_316_p1 <= icmp_ln22_1_loc_fu_42;
    icmp_ln22_2_fu_328_p2 <= "1" when (signed(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out) > signed(sext_ln22_1_fu_324_p1)) else "0";
    icmp_ln22_fu_288_p2 <= "1" when (signed(h2_1_reg_476) < signed(l2_reg_462)) else "0";
    icmp_ln7_fu_218_p2 <= "1" when (signed(size_fu_34) < signed(n)) else "0";
    l1_fu_381_p2 <= std_logic_vector(unsigned(h2_1_reg_476) + unsigned(ap_const_lv32_1));
    l2_fu_229_p2 <= std_logic_vector(unsigned(l1_2_reg_94) + unsigned(size_fu_34));
    select_ln22_fu_338_p3 <= 
        trunc_ln22_fu_334_p1 when (icmp_ln22_2_fu_328_p2(0) = '1') else 
        add_ln29_fu_319_p2;
    select_ln35_fu_359_p3 <= 
        h2_1_reg_476 when (empty_reg_530(0) = '1') else 
        l2_reg_462;
        sext_ln22_1_fu_324_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(add_ln29_fu_319_p2),64));

        sext_ln22_fu_277_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(l1_2_reg_94),33));

    size_2_fu_239_p2 <= std_logic_vector(shift_left(unsigned(size_fu_34),to_integer(unsigned('0' & ap_const_lv32_1(31-1 downto 0)))));
    sub7_fu_199_p2 <= std_logic_vector(unsigned(n) + unsigned(ap_const_lv32_FFFFFFFF));
    sub_ln22_fu_281_p2 <= std_logic_vector(unsigned(ap_const_lv33_1) - unsigned(sext_ln22_fu_277_p1));
    sub_ln35_fu_364_p2 <= std_logic_vector(unsigned(ap_const_lv32_1) - unsigned(l2_reg_462));

    temp_address0_assign_proc : process(icmp_ln22_reg_496, ap_CS_fsm_state8, ap_CS_fsm_state11, grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_address0, grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_address0, grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_address0, grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_address0, grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_address0, ap_CS_fsm_state12, ap_CS_fsm_state6, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            temp_address0 <= grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_address0;
        elsif (((icmp_ln22_reg_496 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            temp_address0 <= grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            temp_address0 <= grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp_address0 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_address0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            temp_address0 <= grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_address0;
        else 
            temp_address0 <= "XXXXX";
        end if; 
    end process;


    temp_ce0_assign_proc : process(icmp_ln22_reg_496, ap_CS_fsm_state8, ap_CS_fsm_state11, grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_ce0, grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_ce0, grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_ce0, grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_ce0, grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_ce0, ap_CS_fsm_state12, ap_CS_fsm_state6, ap_CS_fsm_state14)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state14)) then 
            temp_ce0 <= grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_ce0;
        elsif (((icmp_ln22_reg_496 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            temp_ce0 <= grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            temp_ce0 <= grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp_ce0 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_ce0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            temp_ce0 <= grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_ce0;
        else 
            temp_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    temp_d0_assign_proc : process(icmp_ln22_reg_496, ap_CS_fsm_state8, ap_CS_fsm_state11, grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_d0, grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_d0, grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_d0, grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_d0, ap_CS_fsm_state12, ap_CS_fsm_state6)
    begin
        if (((icmp_ln22_reg_496 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            temp_d0 <= grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            temp_d0 <= grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp_d0 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_d0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            temp_d0 <= grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_d0;
        else 
            temp_d0 <= "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX";
        end if; 
    end process;


    temp_we0_assign_proc : process(icmp_ln22_reg_496, ap_CS_fsm_state8, ap_CS_fsm_state11, grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_we0, grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_we0, grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_we0, grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_we0, ap_CS_fsm_state12, ap_CS_fsm_state6)
    begin
        if (((icmp_ln22_reg_496 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state11))) then 
            temp_we0 <= grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state8)) then 
            temp_we0 <= grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state6)) then 
            temp_we0 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_we0;
        elsif ((ap_const_logic_1 = ap_CS_fsm_state12)) then 
            temp_we0 <= grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_we0;
        else 
            temp_we0 <= ap_const_logic_0;
        end if; 
    end process;

    trunc_ln22_fu_334_p1 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out(32 - 1 downto 0);
    xor_ln15_fu_258_p2 <= (icmp_ln15_fu_253_p2 xor ap_const_lv1_1);
    xor_ln22_fu_292_p2 <= (icmp_ln22_fu_288_p2 xor ap_const_lv1_1);
end behav;
