// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module group3_mergeSort (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        arr_read,
        n,
        ap_return
);

parameter    ap_ST_fsm_state1 = 14'd1;
parameter    ap_ST_fsm_state2 = 14'd2;
parameter    ap_ST_fsm_state3 = 14'd4;
parameter    ap_ST_fsm_state4 = 14'd8;
parameter    ap_ST_fsm_state5 = 14'd16;
parameter    ap_ST_fsm_state6 = 14'd32;
parameter    ap_ST_fsm_state7 = 14'd64;
parameter    ap_ST_fsm_state8 = 14'd128;
parameter    ap_ST_fsm_state9 = 14'd256;
parameter    ap_ST_fsm_state10 = 14'd512;
parameter    ap_ST_fsm_state11 = 14'd1024;
parameter    ap_ST_fsm_state12 = 14'd2048;
parameter    ap_ST_fsm_state13 = 14'd4096;
parameter    ap_ST_fsm_state14 = 14'd8192;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] arr_read;
input  [31:0] n;
output  [31:0] ap_return;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [13:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg   [31:0] reg_192;
wire    ap_CS_fsm_state3;
wire   [0:0] icmp_ln10_fu_234_p2;
wire    ap_CS_fsm_state5;
wire   [31:0] sub7_fu_199_p2;
reg   [31:0] sub7_reg_445;
wire   [31:0] add_ln13_fu_223_p2;
reg   [31:0] add_ln13_reg_456;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln7_fu_218_p2;
wire   [31:0] l2_fu_229_p2;
reg   [31:0] l2_reg_462;
wire   [31:0] h2_1_fu_264_p3;
reg   [31:0] h2_1_reg_476;
wire    ap_CS_fsm_state4;
wire   [31:0] h1_fu_271_p2;
reg   [31:0] h1_reg_485;
wire   [32:0] sub_ln22_fu_281_p2;
reg   [32:0] sub_ln22_reg_491;
wire   [0:0] icmp_ln22_fu_288_p2;
reg   [0:0] icmp_ln22_reg_496;
wire   [0:0] xor_ln22_fu_292_p2;
reg   [0:0] xor_ln22_reg_500;
wire   [31:0] select_ln22_fu_338_p3;
reg   [31:0] select_ln22_reg_520;
wire    ap_CS_fsm_state7;
wire   [0:0] icmp_ln22_1_loc_load_load_fu_316_p1;
wire   [31:0] add_ln31_fu_350_p2;
wire    ap_CS_fsm_state8;
wire   [0:0] empty_fu_355_p2;
reg   [0:0] empty_reg_530;
wire    ap_CS_fsm_state9;
reg   [31:0] arr_0_load11_reg_535;
wire    ap_CS_fsm_state10;
wire   [31:0] add_ln35_1_fu_375_p2;
reg   [31:0] add_ln35_1_reg_540;
wire   [31:0] l1_fu_381_p2;
wire    ap_CS_fsm_state11;
reg   [4:0] temp_address0;
reg    temp_ce0;
reg    temp_we0;
reg   [31:0] temp_d0;
wire   [31:0] temp_q0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_done;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_idle;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_ready;
wire   [4:0] grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_address0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_ce0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_we0;
wire   [31:0] grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_d0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_done;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_idle;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_ready;
wire   [4:0] grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_address0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_ce0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_we0;
wire   [31:0] grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_d0;
wire   [31:0] grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_out;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_out_ap_vld;
wire   [31:0] grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out_ap_vld;
wire   [63:0] grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out_ap_vld;
wire   [31:0] grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out_ap_vld;
wire   [31:0] grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_i_1_out;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_i_1_out_ap_vld;
wire   [0:0] grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out_ap_vld;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_idle;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_ready;
wire   [4:0] grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_address0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_ce0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_we0;
wire   [31:0] grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_d0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_done;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_idle;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_ready;
wire   [4:0] grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_address0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_ce0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_we0;
wire   [31:0] grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_d0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_done;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_idle;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_ready;
wire   [4:0] grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_address0;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_ce0;
wire   [31:0] grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out;
wire    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out_ap_vld;
reg   [31:0] k_reg_82;
reg   [31:0] ap_phi_mux_k_4_lcssa_phi_fu_120_p4;
reg    ap_block_state11_on_subcall_done;
reg   [31:0] l1_2_reg_94;
reg   [31:0] k_4_reg_106;
reg   [31:0] k_4_lcssa_reg_116;
reg    grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg;
wire    ap_CS_fsm_state12;
reg    grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg;
wire    ap_CS_fsm_state6;
reg   [31:0] phi_ln22_1_loc_fu_58;
reg   [31:0] k_1_loc_fu_50;
reg   [0:0] icmp_ln22_1_loc_fu_42;
reg    grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg;
reg    grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg;
reg    grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg;
wire    ap_CS_fsm_state13;
wire    ap_CS_fsm_state14;
reg   [31:0] arr_0_fu_38;
reg   [31:0] size_fu_34;
wire   [31:0] size_2_fu_239_p2;
wire   [31:0] h2_fu_249_p2;
wire   [0:0] icmp_ln15_fu_253_p2;
wire   [0:0] xor_ln15_fu_258_p2;
wire  signed [32:0] sext_ln22_fu_277_p1;
wire  signed [31:0] add_ln29_fu_319_p2;
wire  signed [63:0] sext_ln22_1_fu_324_p1;
wire   [0:0] icmp_ln22_2_fu_328_p2;
wire   [31:0] trunc_ln22_fu_334_p1;
wire   [31:0] add_ln31_1_fu_346_p2;
wire   [31:0] select_ln35_fu_359_p3;
wire   [31:0] add_ln35_fu_369_p2;
wire   [31:0] sub_ln35_fu_364_p2;
reg   [13:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
reg    ap_ST_fsm_state6_blk;
wire    ap_ST_fsm_state7_blk;
reg    ap_ST_fsm_state8_blk;
wire    ap_ST_fsm_state9_blk;
wire    ap_ST_fsm_state10_blk;
reg    ap_ST_fsm_state11_blk;
reg    ap_ST_fsm_state12_blk;
wire    ap_ST_fsm_state13_blk;
reg    ap_ST_fsm_state14_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 14'd1;
#0 grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg = 1'b0;
#0 grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg = 1'b0;
#0 grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg = 1'b0;
#0 grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg = 1'b0;
#0 grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg = 1'b0;
end

group3_mergeSort_temp_RAM_AUTO_1R1W #(
    .DataWidth( 32 ),
    .AddressRange( 30 ),
    .AddressWidth( 5 ))
temp_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(temp_address0),
    .ce0(temp_ce0),
    .we0(temp_we0),
    .d0(temp_d0),
    .q0(temp_q0)
);

group3_mergeSort_Pipeline_VITIS_LOOP_39_6 grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start),
    .ap_done(grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_done),
    .ap_idle(grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_idle),
    .ap_ready(grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_ready),
    .sext_ln39(k_reg_82),
    .sext_ln7(n),
    .temp_address0(grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_address0),
    .temp_ce0(grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_ce0),
    .temp_we0(grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_we0),
    .temp_d0(grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_d0),
    .arr_0(reg_192)
);

group3_mergeSort_Pipeline_VITIS_LOOP_22_3 grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start),
    .ap_done(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_done),
    .ap_idle(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_idle),
    .ap_ready(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_ready),
    .k(k_reg_82),
    .sext_ln22_3(sub_ln22_reg_491),
    .l1_2_cast2(l1_2_reg_94),
    .sext_ln22(k_reg_82),
    .l1_2(l1_2_reg_94),
    .h1(h1_reg_485),
    .icmp_ln22(xor_ln22_reg_500),
    .temp_address0(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_address0),
    .temp_ce0(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_ce0),
    .temp_we0(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_we0),
    .temp_d0(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_d0),
    .arr_0(reg_192),
    .phi_ln22_out(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_out),
    .phi_ln22_out_ap_vld(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_out_ap_vld),
    .phi_ln22_1_out(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out),
    .phi_ln22_1_out_ap_vld(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out_ap_vld),
    .indvars_iv1_out(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out),
    .indvars_iv1_out_ap_vld(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out_ap_vld),
    .k_1_out(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out),
    .k_1_out_ap_vld(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out_ap_vld),
    .i_1_out(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_i_1_out),
    .i_1_out_ap_vld(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_i_1_out_ap_vld),
    .icmp_ln22_1_out(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out),
    .icmp_ln22_1_out_ap_vld(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out_ap_vld)
);

group3_mergeSort_Pipeline_VITIS_LOOP_29_4 grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start),
    .ap_done(grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done),
    .ap_idle(grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_idle),
    .ap_ready(grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_ready),
    .sext_ln29_2(k_1_loc_fu_50),
    .sext_ln29(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_i_1_out),
    .temp_address0(grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_address0),
    .temp_ce0(grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_ce0),
    .temp_we0(grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_we0),
    .temp_d0(grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_d0),
    .arr_0(reg_192),
    .sext_ln29_1(h1_reg_485)
);

group3_mergeSort_Pipeline_VITIS_LOOP_31_5 grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start),
    .ap_done(grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_done),
    .ap_idle(grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_idle),
    .ap_ready(grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_ready),
    .sext_ln31_2(k_4_reg_106),
    .sext_ln31(l2_reg_462),
    .temp_address0(grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_address0),
    .temp_ce0(grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_ce0),
    .temp_we0(grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_we0),
    .temp_d0(grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_d0),
    .arr_0(arr_0_load11_reg_535),
    .sext_ln31_1(h2_1_reg_476)
);

group3_mergeSort_Pipeline_VITIS_LOOP_42_7 grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start),
    .ap_done(grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_done),
    .ap_idle(grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_idle),
    .ap_ready(grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_ready),
    .n(n),
    .temp_address0(grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_address0),
    .temp_ce0(grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_ce0),
    .temp_q0(temp_q0),
    .arr_1_out(grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out),
    .arr_1_out_ap_vld(grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state5)) begin
            grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg <= 1'b1;
        end else if ((grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_ready == 1'b1)) begin
            grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln22_1_loc_load_load_fu_316_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
            grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg <= 1'b1;
        end else if ((grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_ready == 1'b1)) begin
            grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state10)) begin
            grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg <= 1'b1;
        end else if ((grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_ready == 1'b1)) begin
            grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln10_fu_234_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
            grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg <= 1'b1;
        end else if ((grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_ready == 1'b1)) begin
            grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state13)) begin
            grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg <= 1'b1;
        end else if ((grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_ready == 1'b1)) begin
            grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        arr_0_fu_38 <= arr_read;
    end else if (((grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out_ap_vld == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
        arr_0_fu_38 <= grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_arr_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln22_reg_496 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
        k_4_lcssa_reg_116 <= k_4_reg_106;
    end else if (((icmp_ln22_reg_496 == 1'd0) & (1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        k_4_lcssa_reg_116 <= add_ln35_1_reg_540;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln22_1_loc_load_load_fu_316_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
        k_4_reg_106 <= k_1_loc_fu_50;
    end else if (((1'b1 == ap_CS_fsm_state8) & (grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done == 1'b1))) begin
        k_4_reg_106 <= add_ln31_fu_350_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        k_reg_82 <= ap_phi_mux_k_4_lcssa_phi_fu_120_p4;
    end else if (((icmp_ln7_fu_218_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        k_reg_82 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
        l1_2_reg_94 <= l1_fu_381_p2;
    end else if (((icmp_ln7_fu_218_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        l1_2_reg_94 <= 32'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        size_fu_34 <= 32'd1;
    end else if (((icmp_ln10_fu_234_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
        size_fu_34 <= size_2_fu_239_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln7_fu_218_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        add_ln13_reg_456 <= add_ln13_fu_223_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state10)) begin
        add_ln35_1_reg_540 <= add_ln35_1_fu_375_p2;
        arr_0_load11_reg_535 <= arr_0_fu_38;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln22_reg_496 == 1'd0) & (1'b1 == ap_CS_fsm_state9))) begin
        empty_reg_530 <= empty_fu_355_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        h1_reg_485 <= h1_fu_271_p2;
        icmp_ln22_reg_496 <= icmp_ln22_fu_288_p2;
        sub_ln22_reg_491 <= sub_ln22_fu_281_p2;
        xor_ln22_reg_500 <= xor_ln22_fu_292_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        h2_1_reg_476 <= h2_1_fu_264_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out_ap_vld == 1'b1))) begin
        icmp_ln22_1_loc_fu_42 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_icmp_ln22_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out_ap_vld == 1'b1))) begin
        k_1_loc_fu_50 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_k_1_out;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        l2_reg_462 <= l2_fu_229_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out_ap_vld == 1'b1))) begin
        phi_ln22_1_loc_fu_58 <= grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_1_out;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((icmp_ln10_fu_234_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3)))) begin
        reg_192 <= arr_0_fu_38;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln22_1_loc_load_load_fu_316_p1 == 1'd1) & (1'b1 == ap_CS_fsm_state7))) begin
        select_ln22_reg_520 <= select_ln22_fu_338_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        sub7_reg_445 <= sub7_fu_199_p2;
    end
end

assign ap_ST_fsm_state10_blk = 1'b0;

always @ (*) begin
    if ((1'b1 == ap_block_state11_on_subcall_done)) begin
        ap_ST_fsm_state11_blk = 1'b1;
    end else begin
        ap_ST_fsm_state11_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_done == 1'b0)) begin
        ap_ST_fsm_state12_blk = 1'b1;
    end else begin
        ap_ST_fsm_state12_blk = 1'b0;
    end
end

assign ap_ST_fsm_state13_blk = 1'b0;

always @ (*) begin
    if ((grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_done == 1'b0)) begin
        ap_ST_fsm_state14_blk = 1'b1;
    end else begin
        ap_ST_fsm_state14_blk = 1'b0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if ((grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_done == 1'b0)) begin
        ap_ST_fsm_state6_blk = 1'b1;
    end else begin
        ap_ST_fsm_state6_blk = 1'b0;
    end
end

assign ap_ST_fsm_state7_blk = 1'b0;

always @ (*) begin
    if ((grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done == 1'b0)) begin
        ap_ST_fsm_state8_blk = 1'b1;
    end else begin
        ap_ST_fsm_state8_blk = 1'b0;
    end
end

assign ap_ST_fsm_state9_blk = 1'b0;

always @ (*) begin
    if ((((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)) | ((icmp_ln7_fu_218_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln22_reg_496 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        ap_phi_mux_k_4_lcssa_phi_fu_120_p4 = add_ln35_1_reg_540;
    end else begin
        ap_phi_mux_k_4_lcssa_phi_fu_120_p4 = k_4_lcssa_reg_116;
    end
end

always @ (*) begin
    if (((icmp_ln7_fu_218_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        temp_address0 = grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_address0;
    end else if (((icmp_ln22_reg_496 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        temp_address0 = grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_address0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        temp_address0 = grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_address0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_address0 = grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_address0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_address0 = grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_address0;
    end else begin
        temp_address0 = 'bx;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state14)) begin
        temp_ce0 = grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_temp_ce0;
    end else if (((icmp_ln22_reg_496 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        temp_ce0 = grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_ce0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        temp_ce0 = grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_ce0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_ce0 = grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_ce0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_ce0 = grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_ce0;
    end else begin
        temp_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln22_reg_496 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        temp_d0 = grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_d0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        temp_d0 = grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_d0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_d0 = grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_d0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_d0 = grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_d0;
    end else begin
        temp_d0 = 'bx;
    end
end

always @ (*) begin
    if (((icmp_ln22_reg_496 == 1'd0) & (1'b1 == ap_CS_fsm_state11))) begin
        temp_we0 = grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_temp_we0;
    end else if ((1'b1 == ap_CS_fsm_state8)) begin
        temp_we0 = grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_temp_we0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        temp_we0 = grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_temp_we0;
    end else if ((1'b1 == ap_CS_fsm_state12)) begin
        temp_we0 = grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_temp_we0;
    end else begin
        temp_we0 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln7_fu_218_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((icmp_ln10_fu_234_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((1'b1 == ap_CS_fsm_state6) & (grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state6;
            end
        end
        ap_ST_fsm_state7 : begin
            if (((icmp_ln22_1_loc_load_load_fu_316_p1 == 1'd0) & (1'b1 == ap_CS_fsm_state7))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state8 : begin
            if (((1'b1 == ap_CS_fsm_state8) & (grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state9;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state8;
            end
        end
        ap_ST_fsm_state9 : begin
            if (((icmp_ln22_reg_496 == 1'd1) & (1'b1 == ap_CS_fsm_state9))) begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state10;
            end
        end
        ap_ST_fsm_state10 : begin
            ap_NS_fsm = ap_ST_fsm_state11;
        end
        ap_ST_fsm_state11 : begin
            if (((1'b0 == ap_block_state11_on_subcall_done) & (1'b1 == ap_CS_fsm_state11))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state11;
            end
        end
        ap_ST_fsm_state12 : begin
            if (((1'b1 == ap_CS_fsm_state12) & (grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state13;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state12;
            end
        end
        ap_ST_fsm_state13 : begin
            ap_NS_fsm = ap_ST_fsm_state14;
        end
        ap_ST_fsm_state14 : begin
            if (((grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state14))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state14;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln13_fu_223_p2 = ($signed(size_fu_34) + $signed(32'd4294967295));

assign add_ln29_fu_319_p2 = (l1_2_reg_94 + add_ln13_reg_456);

assign add_ln31_1_fu_346_p2 = (phi_ln22_1_loc_fu_58 + grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_phi_ln22_out);

assign add_ln31_fu_350_p2 = (add_ln31_1_fu_346_p2 + select_ln22_reg_520);

assign add_ln35_1_fu_375_p2 = (add_ln35_fu_369_p2 + sub_ln35_fu_364_p2);

assign add_ln35_fu_369_p2 = (select_ln35_fu_359_p3 + k_4_reg_106);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state10 = ap_CS_fsm[32'd9];

assign ap_CS_fsm_state11 = ap_CS_fsm[32'd10];

assign ap_CS_fsm_state12 = ap_CS_fsm[32'd11];

assign ap_CS_fsm_state13 = ap_CS_fsm[32'd12];

assign ap_CS_fsm_state14 = ap_CS_fsm[32'd13];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_state8 = ap_CS_fsm[32'd7];

assign ap_CS_fsm_state9 = ap_CS_fsm[32'd8];

always @ (*) begin
    ap_block_state11_on_subcall_done = ((icmp_ln22_reg_496 == 1'd0) & (grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_done == 1'b0));
end

assign ap_return = arr_0_fu_38;

assign empty_fu_355_p2 = (($signed(h2_1_reg_476) > $signed(l2_reg_462)) ? 1'b1 : 1'b0);

assign grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start = grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_ap_start_reg;

assign grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start = grp_mergeSort_Pipeline_VITIS_LOOP_29_4_fu_160_ap_start_reg;

assign grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start = grp_mergeSort_Pipeline_VITIS_LOOP_31_5_fu_169_ap_start_reg;

assign grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start = grp_mergeSort_Pipeline_VITIS_LOOP_39_6_fu_128_ap_start_reg;

assign grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start = grp_mergeSort_Pipeline_VITIS_LOOP_42_7_fu_179_ap_start_reg;

assign h1_fu_271_p2 = ($signed(l2_reg_462) + $signed(32'd4294967295));

assign h2_1_fu_264_p3 = ((xor_ln15_fu_258_p2[0:0] == 1'b1) ? sub7_reg_445 : h2_fu_249_p2);

assign h2_fu_249_p2 = (l2_reg_462 + add_ln13_reg_456);

assign icmp_ln10_fu_234_p2 = (($signed(l2_fu_229_p2) < $signed(n)) ? 1'b1 : 1'b0);

assign icmp_ln15_fu_253_p2 = (($signed(h2_fu_249_p2) < $signed(n)) ? 1'b1 : 1'b0);

assign icmp_ln22_1_loc_load_load_fu_316_p1 = icmp_ln22_1_loc_fu_42;

assign icmp_ln22_2_fu_328_p2 = (($signed(grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out) > $signed(sext_ln22_1_fu_324_p1)) ? 1'b1 : 1'b0);

assign icmp_ln22_fu_288_p2 = (($signed(h2_1_reg_476) < $signed(l2_reg_462)) ? 1'b1 : 1'b0);

assign icmp_ln7_fu_218_p2 = (($signed(size_fu_34) < $signed(n)) ? 1'b1 : 1'b0);

assign l1_fu_381_p2 = (h2_1_reg_476 + 32'd1);

assign l2_fu_229_p2 = (l1_2_reg_94 + size_fu_34);

assign select_ln22_fu_338_p3 = ((icmp_ln22_2_fu_328_p2[0:0] == 1'b1) ? trunc_ln22_fu_334_p1 : add_ln29_fu_319_p2);

assign select_ln35_fu_359_p3 = ((empty_reg_530[0:0] == 1'b1) ? h2_1_reg_476 : l2_reg_462);

assign sext_ln22_1_fu_324_p1 = add_ln29_fu_319_p2;

assign sext_ln22_fu_277_p1 = $signed(l1_2_reg_94);

assign size_2_fu_239_p2 = size_fu_34 << 32'd1;

assign sub7_fu_199_p2 = ($signed(n) + $signed(32'd4294967295));

assign sub_ln22_fu_281_p2 = ($signed(33'd1) - $signed(sext_ln22_fu_277_p1));

assign sub_ln35_fu_364_p2 = (32'd1 - l2_reg_462);

assign trunc_ln22_fu_334_p1 = grp_mergeSort_Pipeline_VITIS_LOOP_22_3_fu_137_indvars_iv1_out[31:0];

assign xor_ln15_fu_258_p2 = (icmp_ln15_fu_253_p2 ^ 1'd1);

assign xor_ln22_fu_292_p2 = (icmp_ln22_fu_288_p2 ^ 1'd1);

endmodule //group3_mergeSort
